name: Publish apps

on:
  repository_dispatch:

permissions:
  contents: write
  id-token: write
  deployments: write

jobs:
  publish-tauri:
    name: Release Tauri apps
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: 'macos-latest'
            args: '--target aarch64-apple-darwin'
          - platform: 'macos-latest'
            args: '--target x86_64-apple-darwin'
          - platform: 'ubuntu-20.04'
            args: ''
          - platform: 'windows-latest'
            args: ''

    runs-on: ${{ matrix.platform }}
    steps:
      - name: Check out numanga.app repo
        uses: actions/checkout@v4
        with:
          repository: er-tech/numanga.app
          ref: dev
          token: ${{ secrets.PAT }}
          
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install Rust stable
        uses: dtolnay/rust-toolchain@stable

      - name: Install Linux dependencies
        if: matrix.platform == 'ubuntu-20.04'
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev libwebkit2gtk-4.0-dev libappindicator3-dev librsvg2-dev patchelf

      - name: Install Mac X86 dependencies
        if: matrix.args == '--target x86_64-apple-darwin'
        run: |
          rustup target add x86_64-apple-darwin

      - name: Install dependencies
        run: npm ci # change this to npm or pnpm depending on which one you use
        
      - name: Set APP version
        run: npm run version:app

      - name: Npm build
        run: npm run build

      - name: Compile and release app
        uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAURI_PRIVATE_KEY: ${{ secrets.TAURI_PRIVATE_KEY }}
          TAURI_KEY_PASSWORD: ${{ secrets.TAURI_KEY_PASSWORD }}
          MACOSX_DEPLOYMENT_TARGET: 10.23.0
        with:
          tagName: v__VERSION__
          releaseName: 'NumAnga v__VERSION__'
          releaseBody: ${{ vars.RELEASE }}
          releaseDraft: false
          prerelease: false
          args: ${{ matrix.args }}
