# Simple workflow for deploying static content to GitHub Pages
name: Deploy to GitHub Pages and publish apps

on:
  workflow_dispatch:
    inputs:
      RELEASE:
        description: 'Release name'
        required: false
        type: string

# Sets the GITHUB_TOKEN permissions to allow deployment to GitHub Pages
permissions:
  contents: write
  id-token: write
  deployments: write

jobs:
  publish-tauri:
    name: Release Tauri apps
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: 'macos-latest' # for Arm based macs (M1 and above).
            args: '--target universal-apple-darwin'
          - platform: 'ubuntu-20.04' # for Tauri v1 you could replace this with ubuntu-20.04.
            args: ''
          - platform: 'windows-latest'
            args: ''

    runs-on: ${{ matrix.platform }}
    steps:
      - name: Check out my other private repo
        uses: actions/checkout@v4
        with:
          repository: er-tech/numanga.app
          ref: dev
          token: ${{ secrets.PAT }}
          
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install Rust stable
        uses: dtolnay/rust-toolchain@stable

      - name: Install Linux dependencies
        if: matrix.platform == 'ubuntu-20.04'
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev libwebkit2gtk-4.0-dev libappindicator3-dev librsvg2-dev patchelf

      - name: Install frontend dependencies
        run: npm ci # change this to npm or pnpm depending on which one you use
        
      - name: Set APP version
        run: npm run version:app

      - name: Npm build
        run: npm run build

      - name: Compile and release app
        uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAURI_PRIVATE_KEY: ${{ secrets.TAURI_PRIVATE_KEY }}
          TAURI_KEY_PASSWORD: ${{ secrets.TAURI_KEY_PASSWORD }}
        with:
          tagName: v__VERSION__ # the action automatically replaces \_\_VERSION\_\_ with the app version
          releaseName: 'Numanga v__VERSION__'
          releaseBody: ${{ inputs.RELEASE }}
          releaseDraft: false
          prerelease: false
